package com.oskr19.easyshop.domain.dto

data class Product (
    val id: String,
    val siteID: String,
    val title: String,
    val subtitle: Any? = null,
    val sellerID: Long,
    val categoryID: String,
    val price: Long,
    val basePrice: Long,
    val originalPrice: Any? = null,
    val currencyID: String,
    val initialQuantity: Long,
    val availableQuantity: Long,
    val soldQuantity: Long,
    val condition: String,
    val permalink: String,
    val thumbnail: String,
    val secureThumbnail: String,
    val pictures: List<Picture>,
    val acceptsMercadopago: Boolean,
    val sellerAddress: SellerAddress,
    val sellerContact: Any? = null,
    val attributes: List<Attribute>,
    val warnings: List<Any?>,
    val variations: List<Variation>,
    val status: String,
    val warranty: String,
    val health: Double
)